openai-php/client

src/Contracts/Transporter.php
src/Resources/Files.php
src/Transporters/HttpTransporter.php
src/ValueObjects/ResourceUri.php
src/ValueObjects/Transporter/Payload.php
tests/Fixtures/File.php
tests/Pest.php
tests/Resources/Files.php

Hi @nunomaduro 
I had a little time and extended the files api a bit.
Was not 100% sure how we should approach the content receiving as this will not follow the REST convention to return an array. Instead it returns just a string.
In order to keep the type definitions as tight as possible I've added a new method (`requestContent()`) on the Transport. Hope this is fine for you. Otherwise just let me know.

Files api: add "receive", "receive content" and "delete"

---

README.md
src/Resources/Files.php
src/ValueObjects/Transporter/Headers.php
src/ValueObjects/Transporter/Payload.php
tests/Fixtures/File.php
tests/Fixtures/MyFile.json
tests/Fixtures/MyFile.jsonl
tests/Resources/Files.php
tests/ValueObjects/Transporter/Payload.php

Hi @nunomaduro 
A PR to add the missing file upload.
The "Content-Type" header creation is a bit ugly but I had no better idea while still using your initial concept with the PSR7-Request creation.

Files api: add "upload"

---

README.md
src/Client.php
src/Resources/FineTunes.php
src/Resources/Models.php
src/Resources/Moderations.php
src/ValueObjects/ResourceUri.php
src/ValueObjects/Transporter/Payload.php
tests/Fixtures/FineTune.php
tests/Fixtures/Model.php
tests/Fixtures/Moderation.php
tests/Resources/FineTunes.php
tests/Resources/Models.php
tests/Resources/Moderations.php

Implemented the last to endpoints.
Looks like the Classifications API is deprecated. Therefore I don't think it's worth implementing it: https://help.openai.com/en/articles/6272941-classifications-transition-guide

Add missing api endpoints

---

src/Transporters/HttpTransporter.php

`->getContents()` only reads the stream from wherever the current position is - it does not rewind it. This can be hugely problematic if, for example, a logging middleware is attached to the client, which leaves the pointer not at the start of the stream/

Fixed broken getting of body as a string

---

src/Responses/FineTunes/RetrieveResponse.php

#38 
I was getting the same error as this issue, this resolves it for me. Simply returning an empty array for the 'events' key if it's not present in the response from OpenAI

Fix undefined Array Key 'events'

---

README.md
src/Responses/Completions/CreateResponseChoice.php
tests/Responses/Completions/CreateResponseChoice.php

A recent change to the OpenAI API means that finish_reason is sometimes returned as NULL and causes an exception.
This change allows finishReason to be nullable.

Make finishReason nullable #51

---

README.md
composer.json
src/Factory.php
src/OpenAI.php
src/Transporters/HttpTransporter.php
src/ValueObjects/Transporter/Headers.php
src/ValueObjects/Transporter/Payload.php
src/ValueObjects/Transporter/QueryParams.php
tests/Arch.php
tests/OpenAI.php
tests/Pest.php
tests/Transporters/HttpTransporter.php
tests/ValueObjects/Transporter/Payload.php

This adds the ability to configure the client instance via a new factory:
Excerpt from the updated README.
```php
$yourApiKey = getenv('YOUR_API_KEY');
$client = OpenAI::factory()
->withApiKey($yourApiKey)
->withOrganization('your-organization') // default: null
->withBaseUrl('openai.example.com/v1') // default: api.openai.com/v1
->withHttpHeader('X-My-Header', 'foo')
->withHttpClient(new \GuzzleHttp\Client([])) // default: HTTP client found using PSR-18 HTTP Client Discovery
->make();
```
This change is breaking as the "guzzlehttp/guzzle" has been removed. Existing projects without an explicitly installed HTTP client have to install the Guzzle Client manually:
```bash
composer require guzzlehttp/guzzle
``` 
With this change we can resolve various issues:
- #30 
- #31 
- #39 
- #65
- #67

feat: add client factory

---

src/Factory.php

when you are adding API key from configuration file it can add whitespace character(s) - we should trim that

trim api key

---

src/Responses/Chat/CreateStreamedResponseDelta.php
tests/Fixtures/Chat.php
tests/Responses/Chat/CreateStreamdResponseChoice.php
tests/Responses/Chat/CreateStreamedResponse.php
tests/Responses/Chat/CreateStreamedResponseDelta.php
tests/Responses/FineTunes/ListEventsResponse.php
tests/Responses/Models/ListResponse.php
tests/Responses/Models/RetrieveResponse.php

This PR fixes #104
Added some more tests to the chat stream response classes to ensure all the parsing is done properly.

Fix: the toArray() on streamed chat response deltas should only filter null

---

src/Transporters/HttpTransporter.php
tests/Arch.php
tests/Transporters/HttpTransporter.php

This PR unifies the exception handling between the different request types and HTTP client implementations:
- stream requests are now checked for a json response error and throws the corresponding `ErrorException` like object or content requests already do.
- Guzzle `ClientException`s are checked for json errors before throwing the `TransporterException` and throw a `ErrorException` instead.
Background: For client errors (4xx) the API returns a json error but this wasn't handled with the Guzzle Client yet because Guzzle throws an exception instead of returning the response like the other HTTP clients do.
This change from `TransporterException` to `ErrorException` for 4xx responses with the Guzzle Client is a (minor) breaking change!
This resolves …

[0.5]: unify exception handling

---

src/Responses/Chat/CreateStreamedResponseDelta.php
src/Testing/ClientFake.php
src/Testing/Resources/Concerns/Testable.php

While working #178 - my local suite was failing, as well as main [here](https://github.com/openai-php/client/actions/runs/5593233284/job/15150065665). Personally, outside of my knowledge of why since I assume these tools are versions are locked, but there was no package version change on last merge.
Everything passes locally with `composer test` with this.

Fix Lint failures.

---

src/Responses/Chat/CreateResponseMessage.php
tests/Fixtures/Chat.php
tests/Responses/Chat/CreateResponse.php

The responses from Azure for gpt-35-turbo-16k don't seem to have the content attribute (with OpenAI it's set to null).
This PR fixes the _ErrorException: Undefined array key "content"_ error.

Fix function call responses from Azure throwing errors

---

README.md
composer.json
src/Client.php
src/Contracts/ClientContract.php
src/Contracts/Resources/FineTuningContract.php
src/Enums/FineTuning/FineTuningEventLevel.php
src/Resources/FineTuning.php
src/Responses/FineTuning/ListJobEventsResponse.php
src/Responses/FineTuning/ListJobEventsResponseEvent.php
src/Responses/FineTuning/ListJobEventsResponseEventData.php
src/Responses/FineTuning/ListJobsResponse.php
src/Responses/FineTuning/RetrieveJobResponse.php
src/Responses/FineTuning/RetrieveJobResponseHyperparameters.php
src/Testing/ClientFake.php
src/Testing/Resources/FineTuningTestResource.php
src/Testing/Responses/Fixtures/FineTuning/ListJobEventsResponseFixture.php
src/Testing/Responses/Fixtures/FineTuning/ListJobsResponseFixture.php
src/Testing/Responses/Fixtures/FineTuning/RetrieveJobResponseFixture.php
src/ValueObjects/Transporter/Payload.php
tests/Fixtures/FineTuning.php
tests/Resources/FineTuning.php
tests/Responses/FineTuning/ListJobEventsResponse.php
tests/Responses/FineTuning/ListJobsEventsResponseEvent.php
tests/Responses/FineTuning/ListJobsEventsResponseEventData.php
tests/Responses/FineTuning/ListJobsResponse.php
tests/Responses/FineTuning/RetrieveJobResponse.php
tests/Responses/FineTuning/RetrieveJobResponseHyperparameters.php
tests/Testing/Resources/FineTuningTestResource.php

https://platform.openai.com/docs/api-reference/fine-tuning

[0.7] add fine tuning resource

---

README.md
src/Contracts/Resources/FineTuningContract.php
src/Resources/FineTuning.php
src/Responses/FineTuning/ListJobEventsResponse.php
src/Responses/FineTuning/ListJobsResponse.php
src/Testing/Resources/FineTuningTestResource.php
src/Testing/Responses/Fixtures/FineTuning/ListJobEventsResponseFixture.php
src/Testing/Responses/Fixtures/FineTuning/ListJobsResponseFixture.php
src/ValueObjects/Transporter/Payload.php
tests/Fixtures/FineTuning.php
tests/Resources/FineTuning.php
tests/Responses/FineTuning/ListJobEventsResponse.php
tests/Responses/FineTuning/ListJobsResponse.php

This PR adds the missing "has_more" to the fine tuning jobs and events list responses.
Additionally it adds the missing parameters to filter the jobs list.

Add "has_more" to the fine tuning list responses, add pagination parameters to list jobs request

---

src/Testing/ClientFake.php
src/Testing/Resources/AssistantsFilesTestResource.php
src/Testing/Resources/AssistantsTestResource.php
src/Testing/Resources/ThreadsMessagesFilesTestResource.php
src/Testing/Resources/ThreadsMessagesTestResource.php
src/Testing/Resources/ThreadsRunsStepsTestResource.php
src/Testing/Resources/ThreadsRunsTestResource.php
src/Testing/Resources/ThreadsTestResource.php

This PR adds test resources for Assistants and Threads.

Add test resources for Assistants and Threads

---

src/Responses/Meta/MetaInformation.php
tests/Fixtures/Meta.php
tests/Responses/Meta/MetaInformation.php

Fix handle of the `x-request-id` header when using models that do not return it:
```php
<?php
namespace App\Service;
use OpenAI;
final class Ai
{
private $client;
public function __construct()
{
$this->client = OpenAI::factory()
->withBaseUri('http://localhost:8888/v1')
->make();
}
public function getModels()
{
return $this->client->models()->list();
}
}
```
#253

fix: handle `x-request-id` in `MetaInformation`

---

README.md

Just a quick readme update. It looks like 256x256 is an invalid size for the dall-e-3 model.
See here for supported sizes: https://platform.openai.com/docs/api-reference/images/create#images-create-size

Switch to supported size for dall-e-3

---

src/Responses/Meta/MetaInformation.php
src/Responses/Meta/MetaInformationRateLimit.php
tests/Fixtures/Meta.php
tests/Responses/Meta/MetaInformation.php

Azure only returns a part of the rate limit headers. This PR extracts them properly.

Properly create meta information from azure headers

---

src/Responses/Meta/MetaInformation.php

headers to lowercase

---

src/Responses/Files/RetrieveResponse.php

in the response from OpenAI, bytes can be null. The construct here only accepts integers leading to an error. See bug report for more details (#323)
solves reported bug #323

OpenAI\Responses\Files\RetrieveResponse::__construct(): Argument #3 ($bytes) must be of type int, null given

---

src/Responses/Threads/Runs/Steps/ThreadRunStepResponseFunction.php
tests/Fixtures/ThreadRunSteps.php
tests/Responses/Threads/Runs/Steps/ThreadRunStepResponseFunction.php

When a retrieving the list of run step where their results have not submitted yet, it will trigger an error because `output` is missing from the `$attribute` array.

Add test case for function call with output not submitted yet

---

src/Responses/Threads/Runs/Steps/Delta/ThreadRunStepDeltaResponse.php
src/Responses/Threads/Runs/Steps/ThreadRunStepResponseFunction.php
src/Responses/Threads/Runs/Steps/ThreadRunStepResponseFunctionToolCall.php

Fixes an error when OpenAI's API returns a delta object which has empty tool calls:
`Undefined array key "id" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"id\" at /var/www/html/vendor/openai-php/client/src/Responses/Threads/Runs/Steps/ThreadRunStepResponseFunctionToolCall.php:41)`
```
(
[id] => step_voklimBxRmx023PqaIxX6hya
[object] => thread.run.step.delta
[delta] => Array
(
[step_details] => Array
(
[type] => tool_calls
[tool_calls] => Array
(
[0] => Array
(
[index] => 0
[type] => function
[function] => Array
(
[arguments] => {}
)
)
)
)
)
)
```
This is happening to me for all streamed assistant responses that invoke function calls, the function itself appears in one delta, and the next delta then shows the empty function above.
The current implementation is …

Handle missing attributes for assistant streaming

---

src/Responses/Threads/Runs/Steps/Delta/ThreadRunStepDeltaObject.php
src/Responses/Threads/Runs/Steps/Delta/ThreadRunStepDeltaResponse.php
src/Responses/Threads/Runs/Steps/ThreadRunStepResponseCodeInterpreter.php
src/Responses/Threads/Runs/Steps/ThreadRunStepResponseCodeToolCall.php
src/Responses/Threads/Runs/Steps/ThreadRunStepResponseToolCallsStepDetails.php

Fix missing output parameter on streamed code interpreter outputs

---

src/Responses/Chat/CreateStreamedResponse.php

Adds missing field when streaming called with [`stream_options`](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options)
- #386

Add streamed response usage

---

src/Testing/Responses/Concerns/Fakeable.php
tests/Responses/Assistants/AssistantResponse.php

This PR fixes an error preventing the `metadata` key from being faked.
Fixes #409

Fix faking response metadata

---

README.md
src/Contracts/Resources/ThreadsMessagesContract.php
src/Resources/ThreadsMessages.php
src/Responses/Threads/Messages/ThreadMessageDeleteResponse.php
src/Testing/Resources/ThreadsMessagesTestResource.php
tests/Fixtures/ThreadMessage.php
tests/Resources/ThreadsMessages.php
tests/Responses/Threads/Messages/ThreadMessageDeleteResponse.php
tests/Testing/Resources/ThreadsMessagesTestResource.php

This PR adds the missing endpoint to delete messages from a thread: https://platform.openai.com/docs/api-reference/messages/deleteMessage
Implements #417

Add thread messages delete

---

src/Resources/VectorStoresFileBatches.php
src/Resources/VectorStoresFiles.php
src/Responses/VectorStores/Files/VectorStoreFileListResponse.php
src/Responses/VectorStores/Files/VectorStoreFileResponse.php
src/Responses/VectorStores/Files/VectorStoreFileResponseChunkingStrategyOther.php
src/Responses/VectorStores/Files/VectorStoreFileResponseChunkingStrategyStatic.php
tests/Fixtures/VectorStoreFile.php
tests/Responses/VectorStores/Files/VectorStoreFileResponse.php

This PR adds the newly added chunking strategy to the VectorStoreFileResponse: https://github.com/openai-php/client/discussions/411#discussioncomment-9668693

Add chunking strategy on VectorStoreFileResponse

---

README.md

Simply removing the assistants support section of the readme as it's now released.

update: Remove beta tag from readme

---

src/Testing/Responses/Fixtures/Images/CreateResponseFixture.php

According to issue #340 it is not possible to receive a fake b64_json string when testing the image response. 
The PR solves this issue.
[Issue #340](https://github.com/openai-php/client/issues/340)

Add fake 64_json string to test image response

---

src/Testing/Resources/VectorStoresTestResource.php

The constructor of VectorStoresFilesTestResource and VectorStoresFileBatchesTestResource was receiving an incorrect parameter type, which resulted in a TypeError.

Fix TypeError in VectorStoresFilesTestResource and VectorStoresFileBatchesTestResource

---

README.md

PR will add `stream_options.include_usage` property to chat completions documentation .
- #386

docs: Add stream_options.include_usage property to chat completions documentation

---

src/Resources/VectorStoresFileBatches.php
tests/Resources/VectorStoresFileBatches.php

\OpenAI\Resources\VectorStoresFileBatches::cancel should POST
#433 
[OpenAI API Document](https://platform.openai.com/docs/api-reference/vector-stores-file-batches/cancelBatch)

fix: vector stores file batch cancel payload

---

src/Responses/FineTuning/RetrieveJobResponseError.php

I made a small script whilst I was playing with the lib and testing the openAPi's Fine Tuning:
```
require_once __DIR__ . '/vendor/autoload.php';
$yourApiKey = $_ENV['OPENAI_API_KEY'];
$client = OpenAI::client($yourApiKey);
$response = $client->files()->upload([
'purpose' => 'fine-tune',
'file' => fopen(__DIR__.'/client_data.jsonl', 'r'),
]);
echo($response->id);
$response=$client->fineTuning()->createJob([
'training_file' => $response->id,
'model' => 'gpt-4o-mini-2024-07-18',
'hyperparameters' => [
'n_epochs' => 4,
]
]);
var_dump($response->toArray());
``` 
But that made the script throw the following error:
```
Warning: Undefined array key "code" in /usr/src/app/vendor/openai-php/client/src/Responses/FineTuning/RetrieveJobResponseError.php on line 34
Warning: Undefined array key "param" …
```

Hotfixing missing array keys

---

src/Enums/Moderations/Category.php
src/Responses/Moderations/CreateResponseResult.php
tests/Fixtures/Moderation.php
tests/Resources/Moderations.php

The Omni Moderation models were released, thus deprecating the older models (now referred to as Legacy). This introduced the `illicit` and `illicit/violent` moderation category, but ONLY for Omni. This presented an issue as this library iterated all known types and assumed all models will have it.
Now we only set a Category if we have it and thus support partial support of Omni Moderation.
Ref: https://platform.openai.com/docs/guides/moderation
This does NOT add support for the new `category_applied_input_types` field.

Moderation Omni - New Categories (Illicit*) support.

---

src/Responses/Chat/CreateResponse.php
src/Responses/Chat/CreateResponseUsage.php
src/Responses/Chat/CreateResponseUsageCompletionTokensDetails.php
src/Responses/Chat/CreateResponseUsagePromptTokensDetails.php
tests/Fixtures/Chat.php
tests/Responses/Chat/CreateResponseUsage.php
tests/Responses/Chat/CreateResponseUsageCompletionTokensDetails.php
tests/Responses/Chat/CreateResponseUsagePromptTokensDetails.php

Chat `CreateResponseUsage` object is omitting some properties which have probably been have added in more modern versions of the API which are related to the tokens usage. I think `cached_usage` is specially important (two issues were already requesting this) as this would help users track if their prompts are being cached properly and could directly contribute to save money.
Check the `usage` property for reference: 
https://platform.openai.com/docs/api-reference/chat/object
Fixes #486 #492

fix: add missing properties (specially `cached_usage`) to chat `CreateResponseUsage`

---

src/Exceptions/ErrorException.php
src/Responses/StreamResponse.php
src/Transporters/HttpTransporter.php
tests/Testing/ClientFake.php

I've added the HTTP status code to ErrorException, so it's possible to ignore 404 errors for deleting files that don't exist, if desired. OpenAI doesn't provide an exhaustive enough error response for missing files that I can just quickly and universally check:
```json
{
"error": {
"message": "No such File object: file-testFile",
"type": "invalid_request_error",
"param": "id",
"code": null
}
}
```
As you can see there's no easy error code for missing resources, parsing the message is a terrible idea, so exposing the HTTP status code (404 in this case) enables to perform such simple checks.

HTTP status in ErrorException

---

src/Responses/Assistants/AssistantResponseToolFunctionFunction.php

The description property of `\OpenAI\Responses\Assistants\AssistantResponseToolFunctionFunction` is nullable.
When creating an assistant with a function that does not have a description specified, I received an error:
```
OpenAI\Responses\Assistants\AssistantResponseToolFunctionFunction::__construct(): Argument #1 ($description) must be of type string, null given, called in /var/www/html/vendor/openai-php/client/src/Responses/Assistants/AssistantResponseToolFunctionFunction.php on line 40
```
OpenAI documentation: https://platform.openai.com/docs/api-reference/assistants/createAssistant
Exception
Source of response
Screenshot of documentation

Changed type of the description prop to nullable

---

README.md

Make http $client different from openai $client variable names
Make http $client different from openai $client variable names

Avoid naming confusion of variables

---

src/Responses/Threads/Messages/ThreadMessageResponse.php

Modifying a thread message after creation throws an _attachments_ key exception. This uses the null coalescing operator to provide a fallback if the value is missing.
Resolves #470

Fix 'attachments' key exception on thread message modify

---

.github/workflows/formats.yml

```
Formats P8.1 - ubuntu-latest - prefer-stable
Skipping prestissimo, as it does not support Composer . Specify composer:v1 in tools to use prestissimo
```
This removes prestissimo, as its not really useful anymore with composer:v2.

build: remove prestissimo (unneeded in composer: v2)

---

README.md

Folks are using this repo and copying the first codeblock, which was Completion endpoint which has been deprecated since July 2023. We swap the order so Chat is first (and soon Responses) when that is done.
refs: https://github.com/openai-php/client/issues/491

docs: draw attention away from deprecated completions endpoints

---

src/Responses/Completions/CreateResponseChoice.php
tests/Responses/Completions/CreateResponseChoice.php

In testing OpenAI's legacy completion endpoint. The `logprobs` property is not coming back anymore. Its neither `null` or filled - its simply missing. However, oddly a few API calls later it was back. This appears to be a bug on OpenAI's side with the legacy endpoint.
We can easily handle this though since a natural state of `logprobs` is null. We just expected it to be there.
fixes: #522

fix: correct completion endpoint when logprobs missing

---

src/Resources/VectorStoresFileBatches.php
src/Resources/VectorStoresFiles.php
src/Responses/VectorStores/Files/VectorStoreFileListResponse.php
src/Responses/VectorStores/Files/VectorStoreFileResponse.php
src/Testing/Responses/Fixtures/VectorStores/Files/VectorStoreFileListResponseFixture.php
src/Testing/Responses/Fixtures/VectorStores/Files/VectorStoreFileResponseFixture.php
src/Testing/Responses/Fixtures/VectorStores/VectorStoreListResponseFixture.php
tests/Fixtures/VectorStoreFile.php
tests/Responses/VectorStores/Files/VectorStoreFileResponse.php

The custom attribute (key/value) pair on Vector Store files was missing. They have some limitations, but we just treat them as a generic array of string/string.
> Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard. Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters, booleans, or numbers.
fixes: #537

feat: support 'attributes' on vector store files

---

src/Responses/Chat/CreateResponse.php
src/Responses/Chat/CreateStreamedResponse.php
src/Responses/Embeddings/CreateResponse.php
src/Responses/Embeddings/CreateResponseEmbedding.php
tests/Fixtures/Chat.php
tests/Fixtures/Embedding.php
tests/Responses/Chat/CreateResponse.php
tests/Responses/Chat/CreateStreamedResponse.php
tests/Responses/Embeddings/CreateResponse.php
tests/Responses/Embeddings/CreateResponseEmbedding.php

According to the Google Gemini OpenAI compatibility documentation, OpenAI's official Python and Node.js SDKs are supported for compatibility.
Hope that the PHP version can also be updated to reflect this compatibility :)
https://ai.google.dev/gemini-api/docs/openai
fixes: #526

feat: add OpenAI compatibility support for Google Gemini

---

src/Responses/Chat/CreateResponseChoice.php
tests/Fixtures/Chat.php
tests/Responses/Chat/CreateResponseChoice.php

As it has been some time since I last forked the repository, I noticed from OpenAI's documentation that the chat completion's 'choices' now includes a 'logprobs' field. However, Google Gemini's OpenAI compatibility layer doesn't yet support this field. Therefore, I've modified the code to allow chat completion 'choices' to function without requiring the 'logprobs' field.
fixes: #502

fix: chat completion choices to allow responses without logprobs field

---

src/Responses/StreamResponse.php
tests/Fixtures/Chat.php
tests/Fixtures/Streams/ChatCompletionPing.txt
tests/Resources/Chat.php
tests/Responses/Chat/CreateStreamedResponse.php

When running streaming from Claude in OpenAI compatibility mode we find that Claude returns a payload structure (shortened) like this.
```text
data: {"id":"msg_0111RgCFCqN68mJbev6Rq1cz","choices":[{"index":0,"delta":{"role":"assistant"}}],"created":1744469024,"model":"claude-3-7-sonnet-20250219","object":"chat.completion.chunk"}
data: {"type": "ping"}
data: {"id":"msg_0111RgCFCqN68mJbev6Rq1cz","choices":[{"index":0,"delta":{"content":"Hello!"}}],"created":1744469024,"model":"claude-3-7-sonnet-20250219","object":"chat.completion.chunk"}
data: [DONE]
```
fixes: https://github.com/openai-php/client/issues/555

fix: Support streaming of non-OpenAI models that return "ping"

---

src/Responses/Files/CreateResponse.php
src/Responses/Files/RetrieveResponse.php
src/Responses/FineTunes/RetrieveResponseFile.php
tests/Responses/Files/RetrieveResponse.php

Some Aliyun API responses do not include the `status_details` field, which causes an error when trying to access it. This PR ensures compatibility by setting `status_details` to `null` when it is missing.
- Checks if `status_details` exists in the response before accessing it.
- Defaults `status_details` to `null` if it is not present.
- Ensures compatibility with both OpenAI and Aliyun APIs.
Without this fix, Aliyun API responses that lack `status_details` will cause runtime errors, breaking the client integration.
- Tested with OpenAI API (unchanged behavior).
- Tested with Aliyun API (no more errors when `status_details` is missing).
✅ Fully backward compatible. If `status_details` is present, the behavior remains unchanged.

Add compatibility for aliyun LLM APIs

---

src/Contracts/Resources/FilesContract.php
src/Resources/Files.php
src/Testing/Resources/FilesTestResource.php
tests/Testing/Resources/FilesTestResource.php

[From a discussion on Twitter...](https://x.com/assertchris/status/1910355384562229390)
TL;DR:
You can't currently pass parameters to the files list request, which means you can only ever get the first 10. This PR adds the ability to paginate, change limit etc.
Unrelated: the refactor commands in readme don't appear to work. Everything else passed.
fixes: #500

Allow arguments to be passed to files list request

---

README.md
src/Contracts/Resources/VectorStoresContract.php
src/Resources/VectorStores.php
src/Responses/VectorStores/Search/VectorStoreSearchResponse.php
src/Responses/VectorStores/Search/VectorStoreSearchResponseContent.php
src/Responses/VectorStores/Search/VectorStoreSearchResponseFile.php
src/Testing/Resources/VectorStoresTestResource.php
src/Testing/Responses/Fixtures/VectorStores/Search/VectorStoreSearchResponseContentFixture.php
src/Testing/Responses/Fixtures/VectorStores/Search/VectorStoreSearchResponseFileFixture.php
src/Testing/Responses/Fixtures/VectorStores/Search/VectorStoreSearchResponseFixture.php
tests/Fixtures/VectorStoreSearch.php
tests/Responses/VectorStores/Search/VectorStoreSearchResponse.php

Added support for missing searching vector stores with the OpenAI API via the POST endpoint `/vector_stores/{vector_store_id}/search` as described [in OpenAI Search vector store docs page](https://platform.openai.com/docs/api-reference/vector-stores/search). This implementation allows users to search a vector store for relevant chunks based on both a text query and optional file attributes filter.
Key features of this implementation:
- Support for text and hybrid semantic queries
- File attribute filtering to refine search results
- Pagination support through has_more and next_page fields
- Detailed response objects including file metadata and content chunks
- Comprehensive type safety with proper response typing

Search vector store

---

src/Responses/Chat/CreateResponseUsageCompletionTokensDetails.php
src/Responses/Chat/CreateResponseUsagePromptTokensDetails.php
tests/Fixtures/Chat.php
tests/Responses/Chat/CreateResponse.php
tests/Responses/Chat/CreateResponseChoice.php
tests/Responses/Chat/CreateResponseUsage.php

- [] New Feature
Inconsistencies in how token usage details are handled from provider OpenRouter.
- Ensures consistent output structure for token usage details (prompt_tokens_details and completion_tokens_details)
- Includes all token fields in responses
- Fix error on TypeError for CreateResponseUsageCompletionTokensDetails where $acceptedPredictionTokens must be of type int, null given
OpenRouter and OpenAI responses had different structures, with OpenRouter omitting zero-valued token fields while OpenAI included them:
- OpenRouter omitted audio_tokens, accepted_prediction_tokens, and rejected_prediction_tokens
- OpenAI included all token fields regardless of value
Both providers now return consistent response structures with all token fields present:
- All responses include complete …

OpenRouter: Fix token usage response

---

src/Responses/Models/ListResponse.php
src/Responses/Models/RetrieveResponse.php
tests/Fixtures/Model.php
tests/Responses/Models/RetrieveResponse.php

It seems the 'created' field doesn't always exist on some of these APIs. I experienced the issue with Google Gemini, but after I worked on this code briefly I noticed another pull request existed that was addressing issues with Azure, but by falling back to 0 instead of null. 
This just marks the field as nullable and yields null. I think it's worth discussing (as noted in the linked PR) whether this approach is better or if created should fall back to '0' or something similar.
fixes: https://github.com/openai-php/client/issues/566
closes: https://github.com/openai-php/client/pull/458

Fix gemini list models

---

src/Resources/Images.php
src/Responses/Images/CreateResponse.php
src/Responses/Images/EditResponse.php
src/Responses/Images/ImageResponseUsage.php
src/Responses/Images/ImageResponseUsageInputTokensDetails.php
src/Responses/Images/VariationResponse.php
tests/Fixtures/Image.php
tests/Resources/Images.php
tests/Responses/Images/CreateResponse.php
tests/Responses/Images/EditResponse.php
tests/Responses/Images/VariationResponse.php

This PR adds support for tracking token usage in image generation, editing, and variation responses that got introduced in `gpt-image-1`  (https://platform.openai.com/docs/api-reference/images/object). 
The changes include:
1. Added new response classes `ImageResponseUsage` and `ImageResponseUsageInputTokensDetails` to handle usage data
2. Updated existing image response classes (`CreateResponse`, `EditResponse`, and `VariationResponse`) to include usage information
3. Added comprehensive test coverage for the new usage tracking functionality
4. Updated type definitions and documentation to reflect the new usage fields
The usage information includes:
- Total tokens used
- Input tokens
- Output tokens
- Detailed breakdown of input tokens (text tokens and image tokens)
This feature allows …

feat(OpenAI): Add Image Response usage

---

src/Responses/Responses/CreateResponse.php
tests/Fixtures/Responses.php
tests/Responses/Responses/CreateResponse.php

The Python/JavaScript official SDKs offer `output_text` since its kinda a PITA to get the text from Responses API amongst all the other return types. I've followed the [implementation](https://github.com/openai/openai-node/blob/master/src/lib/ResponsesParser.ts#L247) in the Node SDK to guide the PHP one.
https://platform.openai.com/docs/api-reference/responses/object

feat(OpenAI) - Add helper method 'output_text' to Responses API

---

src/Testing/Responses/Concerns/Fakeable.php
tests/Fixtures/Responses.php
tests/Responses/Responses/CreateResponse.php

Just augments test suite for Responses API
refs: #581

test(OpenAI): augment testing for fake() on Responses API

---

src/Client.php
src/Contracts/ClientContract.php
src/Contracts/Resources/RealtimeContract.php
src/Resources/Realtime.php
src/Responses/Realtime/Session/ClientSecret.php
src/Responses/Realtime/Session/InputAudioTranscription.php
src/Responses/Realtime/Session/TurnDetection.php
src/Responses/Realtime/SessionClientSecret.php
src/Responses/Realtime/SessionResponse.php
src/Responses/Realtime/Tools/FunctionTool.php
src/Responses/Realtime/TranscriptionSession/InputAudioTranscription.php
src/Responses/Realtime/TranscriptionSessionResponse.php
src/Testing/ClientFake.php
src/Testing/Resources/RealtimeTestResource.php
src/Testing/Responses/Fixtures/Realtime/SessionResponseFixture.php
src/Testing/Responses/Fixtures/Realtime/TranscriptionSessionResponseFixture.php
tests/Fixtures/Realtime.php
tests/Resources/Realtime.php
tests/Responses/Realtime/SessionResponse.php
tests/Responses/Realtime/TranscriptionSessionResponse.php
tests/Testing/Resources/RealtimeTestResource.php

This adds the endpoints for obtaining ephemeral tokens to use webrtc/websocket real-time.
fixes: #122
fixes: https://github.com/openai-php/client/discussions/589

feat(OpenAI): Realtime Ephermal Tokens

---

README.md

Add documentation for Realtime API

docs(OpenAI): add realtime key docs

---

src/Responses/Models/ListResponse.php
src/Responses/Models/RetrieveResponse.php
tests/Fixtures/Model.php
tests/Responses/Models/RetrieveResponse.php

Adds support for Azure model listing, which uses `created_at` and removes `owned_by`.
fixes: #598

fix(Azure): support azure model.list

---

src/Responses/Responses/CreateResponse.php
src/Responses/Responses/ReferencePromptObject.php
src/Responses/Responses/RetrieveResponse.php
tests/Fixtures/Responses.php
tests/Resources/Responses.php
tests/Responses/Responses/RetrieveResponse.php

If you manage your prompts in OpenAI you have `instructions` (array) and `prompt` (object) returned. We previously only supported a string for `instructions`. Now we have an untyped mixed array of instructions - while we work to type that. This also adds a typed `prompt` object.
fixes: #614

fix(OpenAI): support reused prompts / instructions in Responses

---

README.md

This pull request adds a new usage example to the README demonstrating how to use the OpenAI to understand and describe images using GPT-4o and an accessible image URL.
The example shows how to:
- Provide both a text prompt and an image URL
- Output GPT-4o's vision capabilities in a friendly way
- Showcases advanced GPT-4o usag
- Makes it easy for developers to test image understanding via chat
- Builds on the existing text-only examples by adding multimodal support

docs: add vision example using image URL

---

src/ValueObjects/Transporter/Payload.php

This PR fixes a bug where non-ASCII characters (e.g., German umlauts like `ü` and `Ö`) were being incorrectly escaped in the JSON request body (e.g., to `\u00fc` and `\u00d6`).
1. Create a request with parameters containing special UTF-8 characters. For example:
```php
$client->chat()->create([
'model' => 'gpt-4o',
'messages' => [
['role' => 'user', 'content' => 'Was bedeuten die Umlaute ü und Ö?'],
],
]);
Intercept the request body before it is sent.
Before this fix: The body would contain "... \u00fc und \u00d6".
After this fix: The body now correctly contains "... ü und Ö".

Fix: Add JSON_UNESCAPED_UNICODE to preserve UTF-8 characters

---

src/Responses/Responses/RetrieveResponse.php

The `code_interpreter_call` was not ported to Retrieve method.
fixes: #631

fix(OpenAI): support 'code_interpreter_call' on retrieve response

---

src/Contracts/TransporterContract.php
src/Exceptions/UnserializableResponse.php
src/Resources/Audio.php
src/Responses/Audio/SpeechStreamResponse.php
src/Responses/Meta/MetaInformation.php
src/Responses/Meta/MetaInformationCustom.php
src/Responses/Meta/MetaInformationOpenAI.php
src/Responses/StreamResponse.php
src/Transporters/HttpTransporter.php
src/ValueObjects/Transporter/AdaptableResponse.php
src/ValueObjects/Transporter/Response.php
tests/Arch.php
tests/Datasets/RequestMethods.php
tests/Fixtures/Meta.php
tests/Pest.php
tests/Resources/Audio.php
tests/Responses/Meta/MetaInformation.php
tests/Transporters/HttpTransporter.php

People have been complaining about phantom issues for awhile that parsers get strings, but expect objects. This has been reported a lot of times.
Folks have tried to fix this many times by either overhauling exceptions, detecting http status codes, introducing many new exceptions and all of this is not addressing the root problem.
A long time ago an issue was created to support audio transcription api (https://github.com/openai-php/client/issues/59) and that endpoint has a powerhouse of a feature.
> Select the format of the output, in one of these options: json, text, srt, verbose_json, or vtt
The endpoint can change its return to a variety of types. So base Response classes were adapted to support string/array to handle all of those. The problem however that every single other endpoint …

chore(meta): rework exception handling

---

src/Exceptions/ErrorException.php
src/Responses/StreamResponse.php
src/Transporters/HttpTransporter.php
tests/Testing/ClientFake.php

During #643 I forgot to add raw Response to ErrorException class.

fix(meta): use raw response on ErrorException

---

src/Exceptions/RateLimitException.php
src/Transporters/HttpTransporter.php
tests/Transporters/HttpTransporter.php

Every provider has a different error format which we don't really have a unified parsing mechanism for. However all major players in the scene agree that an HTTP 429 is a rate limit, so we can leverage that. During #643 I believe I missed the non-OpenAI rate limit errors as no direct HTTP status code checking occurs (with exception of a few cases).
This means a rate limit bubbles through to an ErrorException (in case of OpenAI) or in case of another provider - goes onward to the concrete class and crashes.
This adds a tiny check for only HTTP 429 as the payload structure is wildly different between all providers. Userland implementations can use the exception (for backoff/retries) and dig into the include Response for more in-depth handling.
fixes: #587

fix(meta): handle 429 (rate limit) gracefully

---

src/Responses/Responses/Tool/RemoteMcpTool.php
tests/Fixtures/Responses.php
tests/Responses/Responses/Tool/RemoteMcpTool.php

Support when a `require_approval` object comes in as null. Real life test: https://github.com/iBotPeaches/openai-php-laravel-test/commit/5692d0fb26346b8cbbd76b8aa437a0c5c8e3d4b5 
fixes: #666 :imp:

fix(OpenAI): handle null require_approval in Response API

---

src/Actions/Responses/ItemObjects.php
src/Actions/Responses/OutputObjects.php
src/Actions/Responses/OutputText.php
src/Actions/Responses/ToolChoiceObjects.php
src/Actions/Responses/ToolObjects.php
src/Responses/Responses/CreateResponse.php
src/Responses/Responses/ListInputItems.php
src/Responses/Responses/RetrieveResponse.php
tests/Arch.php

During development of #658 I learned the Conversation API has both items (ListInputItems) and output (Response output) that the Response API offers - they are an exact duplication. This is an insane level of duplication of code with the strict typing in place. Earlier iterations of this library had simple endpoints (completion, chat, etc) - as AI has evolved so has the endpoints which means we need to get creative.
The Response API is massive and we are missing a chunk of typed support, this means following the pattern of other endpoints we have a typed response for the Create endpoint, the Retrieve endpoint, the List endpoint, etc. For the most part these endpoints duplicate logic for parsing nested structures like items, data, tools, tool choices, etc.
(duplicated between create, …

refactor(meta): unify response types into Actions

---

src/Responses/Responses/CreateStreamedResponse.php
src/Responses/Responses/Streaming/ReasoningTextDelta.php
src/Responses/Responses/Streaming/ReasoningTextDone.php
tests/Fixtures/Responses.php
tests/Fixtures/Streams/ResponseReasoningTextDelta.txt
tests/Fixtures/Streams/ResponseReasoningTextDone.txt
tests/Responses/Responses/CreateStreamedResponse.php

Adds support for the new reasoning text streaming events introduced in OpenAI's Response API when using models with reasoning capabilities (like gpt-oss):
- `response.reasoning_text.delta` - Emitted when a delta is added to reasoning text content
- `response.reasoning_text.done` - Emitted when reasoning text is completed
These events are documented in the [OpenAI API Reference](https://platform.openai.com/docs/api-reference/responses_streaming/response/reasoning_text) and are used when models perform step-by-step reasoning before
generating their response.
**Changes made:**
- Created `ReasoningTextDelta` class to handle reasoning text delta events
- Created `ReasoningTextDone` class to handle completed reasoning text events
- Updated `CreateStreamedResponse` to recognize and properly …

Add support for reasoning text streaming events

---

CHANGELOG.md

release: v0.16.1

---

README.md
src/Contracts/ClientContract.php

> We now have Assistant-like and Thread-like objects in the Responses API. Learn more in the [migration guide](https://platform.openai.com/docs/guides/assistants/migration). As of August 26th, 2025, we're deprecating the Assistants API, with a sunset date of August 26, 2026.
With OpenAI deprecating Assistants API - its time for us to do so as well.
fixes: #672

chore(OpenAI): deprecate Assistants API officially

---

src/Responses/Images/CreateResponse.php
src/Responses/Images/EditResponse.php
src/Responses/Images/ImageResponseUsage.php
src/Responses/Images/VariationResponse.php
tests/Fixtures/Image.php
tests/Responses/Images/CreateResponse.php
tests/Responses/Images/EditResponse.php
tests/Responses/Images/VariationResponse.php

An OpenAI complaint service has a near compatible implementation but is missing some usage fields. Since this doesn't change anything nullable on the property, just usage - I feel its fine to increase nullability at benefit of supporting another provider.
fixes: #683

fix(Doubao): increase nullability on image usage types

---

src/Responses/Responses/CreateResponse.php

xAI Responses API does not return certain attributes. The `Responses/Responses/CreateResponse` class already allows these fields to be null.
- Added null fallbacks to `instructions, and `truncation` attributes to avoid errors when handling xAI Responses API response _(e.g. grok-4)_
See [xAI Docs](https://docs.x.ai/docs/api-reference#create-new-response)

Fix undefined array key errors for xAI Responses API

---

src/Responses/Responses/Output/OutputMessageContentOutputTextAnnotationsFileCitation.php

After last merge I saw user required to edit 3 types to merge a PR - this should have been the re-used type object.

chore(OpenAI): unify typing on file citation object
