- README.md
- src/Client.php
- src/Resources/Images.php
- src/Responses/Images/CreateResponse.php
- src/Responses/Images/CreateResponseData.php
- src/Responses/Images/EditResponse.php
- src/Responses/Images/EditResponseData.php
- src/Responses/Images/VariationResponse.php
- src/Responses/Images/VariationResponseData.php
- tests/Fixtures/Image.php
- tests/Resources/Images.php
- tests/Responses/Images/CreateResponse.php
- tests/Responses/Images/CreateResponseData.php
- tests/Responses/Images/EditResponse.php
- tests/Responses/Images/EditResponseData.php
- tests/Responses/Images/VariationResponse.php
- tests/Responses/Images/VariationResponseData.php
Dall-E API is now available: https://openai.com/blog/dall-e-api-now-available-in-public-beta/
> feat: add images resource (DALL-E)

- README.md
This PR updates the README to use the latest text-davinci model, so that examples can be easily copy/pasted from the readme.
> Use latest davinci text model

- README.md
Small change to make the FineTunes create example work. It was missing the $response variable declaration.
I'm not sure how to format this PR, I had a look at CONTRIBUTING.md but the pull request template returns a 404 error. 
I had a lot of fun playing around with OpenAI today. This client made it a lot easier so thanks!
> docs: fix FineTunes create method example code

- CONTRIBUTING.md
Missing 'r' at the end of the word refactor
> Fixes typos

- README.md
see https://github.com/openai-php/client/issues/32
> doc: improve "FineTunes" create endpoint documentation in README.md

- .gitignore
- src/Responses/Chat/CreateStreamedResponseDelta.php
There are some lines of code with only three spaces, but I don't know why the github action test:lint passed.
> fix pint lint

- src/Testing/Responses/Concerns/Fakeable.php
- tests/Responses/Completions/CreateResponse.php
- tests/Responses/Embeddings/CreateResponse.php
This PR fixes #122 and https://github.com/openai-php/laravel/issues/41
> fix: embedding create response faking - fixes #122

- src/Exceptions/ErrorException.php
- src/Responses/StreamResponse.php
- src/Transporters/HttpTransporter.php
- tests/Arch.php
- tests/Fixtures/Chat.php
- tests/Fixtures/Streams/ChatCompletionCreateError.txt
- tests/Resources/Chat.php
- tests/Transporters/HttpTransporter.php
This PR fixes three problems:
- Errors are sometimes returned as the first stream response #147 
- Error message is sometimes an array #146 
- Error message is sometimes empty https://github.com/openai-php/laravel/issues/47
> Improve error handling

- CHANGELOG.md
- README.md
- src/Client.php
- src/Contracts/ClientContract.php
- src/Contracts/Resources/CompletionsContract.php
- src/Contracts/Resources/EditsContract.php
- src/Contracts/Resources/EmbeddingsContract.php
- src/Contracts/Resources/FilesContract.php
- src/Contracts/Resources/FineTunesContract.php
- src/Contracts/Resources/ImagesContract.php
- src/Contracts/Resources/ModelsContract.php
- src/Contracts/Resources/ModerationsContract.php
- src/Resources/Completions.php
- src/Resources/Edits.php
- src/Resources/Embeddings.php
- src/Resources/Files.php
- src/Resources/FineTunes.php
- src/Resources/Images.php
- src/Resources/Models.php
- src/Resources/Moderations.php
- tests/Transporters/HttpTransporter.php
Not big deal, just little bit doc updating. When I see old links I am confused. I felt have to update.
> Update api reference links

- src/Resources/FineTuning.php
- src/Responses/FineTuning/ListJobsResponse.php
- src/Responses/FineTuning/RetrieveJobResponse.php
- src/Responses/FineTuning/RetrieveJobResponseHyperparameters.php
- tests/Responses/FineTuning/RetrieveJobResponseHyperparameters.php
Fixes https://github.com/openai-php/client/issues/214
> Fix: nEpochs on RetrieveJobResponseHyperparameters may be string

- README.md
- src/Contracts/Resources/AudioContract.php
- src/Resources/Audio.php
- src/Testing/Resources/AudioTestResource.php
- tests/Fixtures/Audio.php
- tests/Resources/Audio.php
- tests/Testing/Resources/AudioTestResource.php
see https://platform.openai.com/docs/api-reference/audio/createSpeech
> Add audio speech endpoint

- README.md
- src/Resources/Chat.php
- src/Responses/Chat/CreateResponse.php
- src/Responses/Chat/CreateResponseChoice.php
- src/Responses/Chat/CreateResponseMessage.php
- src/Responses/Chat/CreateResponseToolCall.php
- src/Responses/Chat/CreateResponseToolCallFunction.php
- src/Responses/Chat/CreateStreamedResponseDelta.php
- src/Responses/Chat/CreateStreamedResponseFunctionCall.php
- src/Responses/Chat/CreateStreamedResponseToolCall.php
- src/Responses/Chat/CreateStreamedResponseToolCallFunction.php
- src/Testing/Responses/Fixtures/Chat/CreateResponseFixture.php
- tests/Fixtures/Chat.php
- tests/Responses/Chat/CreateResponse.php
- tests/Responses/Chat/CreateResponseMessage.php
- tests/Responses/Chat/CreateResponseToolCall.php
- tests/Responses/Chat/CreateResponseToolCallFunction.php
- tests/Responses/Chat/CreateStreamedResponseDelta.php
https://platform.openai.com/docs/api-reference/chat/create
> Add support for tool_calls on the chat completion endpoint

- src/Responses/Chat/CreateResponseChoice.php
- src/Responses/Chat/CreateStreamedResponseChoice.php
- tests/Fixtures/Chat.php
- tests/Responses/Chat/CreateResponseChoice.php
- tests/Responses/Chat/CreateStreamedResponseChoice.php
Add support for GTP-4 vision on the chat completion endpoint: https://platform.openai.com/docs/guides/vision
> Add support for chat vision response format

- src/Resources/FineTuning.php
- src/Responses/FineTuning/ListJobsResponse.php
- src/Responses/FineTuning/RetrieveJobResponse.php
- src/Responses/FineTuning/RetrieveJobResponseError.php
- src/Responses/FineTuning/RetrieveJobResponseHyperparameters.php
- src/Testing/Responses/Fixtures/FineTuning/RetrieveJobResponseFixture.php
- tests/Fixtures/FineTuning.php
- tests/Resources/FineTuning.php
- tests/Responses/FineTuning/ListJobsResponse.php
- tests/Responses/FineTuning/RetrieveJobResponse.php
- tests/Responses/FineTuning/RetrieveJobResponseError.php
- tests/Responses/FineTuning/RetrieveJobResponseHyperparameters.php
- Add error to Fine-Tuning Job Response
- Update HyperParameters params on Fine-Tuning Job Response
> Add Error properties to Fine-Tuning Job Response

- README.md
Following the removal threads list endpoint I adjusted the README.md . See #271 and the commit f317a9e
> Remove threads list endpoint from README.md

- src/Testing/Responses/Fixtures/Chat/CreateResponseFixture.php
- tests/Responses/Chat/CreateResponse.php
Fix missing system_fingerprint on chat CreateResponse fixture
> Add default system_fingerprint to chat create response fixture

- README.md
Fix heading: "Create streamed" instead of "Created streamed"
> Update README.md : Fix heading: "Create streamed" instead of "Created streamed"

- src/Testing/Responses/Concerns/Fakeable.php
- tests/Testing/ClientFake.php
Fixes https://github.com/openai-php/client/issues/331
> Fix: meta information fake data

- README.md
- src/Resources/Audio.php
- src/Responses/Audio/TranscriptionResponse.php
- src/Responses/Audio/TranscriptionResponseWord.php
- src/ValueObjects/Transporter/Payload.php
- tests/Fixtures/Audio.php
- tests/Responses/Audio/TranscriptionResponse.php
- tests/Responses/Audio/TranscriptionResponseWord.php
Audio: add support for timestamp_granularities
replaces https://github.com/openai-php/client/pull/335
> Audio: add support for timestamp_granularities

- README.md
- src/Client.php
- src/Contracts/ClientContract.php
- src/Contracts/Resources/BatchesContract.php
- src/Resources/Batches.php
- src/Responses/Batches/BatchListResponse.php
- src/Responses/Batches/BatchResponse.php
- src/Responses/Batches/BatchResponseErrors.php
- src/Responses/Batches/BatchResponseErrorsData.php
- src/Responses/Batches/BatchResponseRequestCounts.php
- src/Testing/ClientFake.php
- src/Testing/Resources/BatchesTestResource.php
- src/Testing/Responses/Fixtures/Batches/BatchListResponseFixture.php
- src/Testing/Responses/Fixtures/Batches/BatchResponseFixture.php
- tests/Client.php
- tests/Fixtures/Batches.php
- tests/Resources/Batches.php
- tests/Responses/Batch/BatchListResponse.php
- tests/Responses/Batch/BatchResponse.php
- tests/Responses/Batch/BatchResponseErrors.php
- tests/Responses/Batch/BatchResponseErrorsData.php
- tests/Responses/Batch/BatchResponseRequestCounts.php
- tests/Testing/Resources/BatchTestResource.php
This PR implements the Batch API: https://platform.openai.com/docs/guides/batch
Credits to @The-LoneWolf and his implementation here: https://github.com/openai-php/client/pull/401
> Add batches API endpoint

- src/Resources/Concerns/Transportable.php
Just remove an inaccurate comment I found while digging into the source code.
> Remove inaccurate comment

- src/Responses/Threads/Runs/ThreadRunStreamResponse.php
- [X ] Bug Fix
Added missing event thread.run.incomplete into ThreadRunStreamResponse list of possible response events.
> Added thread.run.incomplete into ThreadRunStreamResponse list of responses

- .github/workflows/formats.yml
> Fixed typo "refactor"

- src/Responses/Threads/Runs/Steps/ThreadRunStepResponse.php
Updates ThreadRunStepResponse to implement the ResponseHasMetaInformationContract.
ThreadRunStepResponse already uses the HasMetaInformation trait, which fulfills the requirements of the contract.
> add ResponseHasMetaInformationContract contract to ThreadRunStepResponse

- README.md
> Corrected readme for current PHP version requirement

- CHANGELOG.md
Looks like the CHANGELOG was not updated. I'm bringing it up to date.
> doc: update changelog (v0.11.2 - v0.13.0)

- README.md
- src/Contracts/Resources/AudioContract.php
- src/Resources/Audio.php
- src/Resources/Concerns/Streamable.php
- src/Responses/Audio/Streaming/Logprobs.php
- src/Responses/Audio/Streaming/TranscriptTextDelta.php
- src/Responses/Audio/Streaming/TranscriptTextDone.php
- src/Responses/Audio/TranscriptionStreamResponse.php
- src/Testing/Resources/AudioTestResource.php
- tests/Fixtures/Audio.php
- tests/Fixtures/Streams/AudioTranscriptionTranscribe.txt
- tests/Resources/Audio.php
Adds support for streaming transcriptions
fixes: #590
> feat(OpenAI): Add support for streaming for transcriptions

- src/Resources/Assistants.php
- src/Responses/Assistants/AssistantResponse.php
- tests/Fixtures/Assistant.php
- tests/Responses/Assistants/AssistantListResponse.php
- tests/Responses/Assistants/AssistantResponse.php
Adds the reasoning model only field of `reasoning_effort` to Assistants
fixes: #519
> fix(OpenAI): add support for reasoningEffort to Assistants

- README.md
Assistants API is deprecated. Drawing attention to it for folks to move to Responses API
> docs(OpenAI): deprecate Assistants API

- README.md
Completions is so old. Its older than Chat and the future is Responses. Mark it as legacy.
> docs(OpenAI): mark Completions as legacy

- CHANGELOG.md
> release: v0.14.0

- composer.json
Introduces Parallel Pint as we spend roughly 29s on every action running Pint, with this change its now 15s which is almost 2x as fast.
> build(meta): add parallel pint

- src/Resources/Threads.php
- src/Resources/ThreadsMessages.php
- src/Resources/ThreadsRuns.php
- src/Resources/ThreadsRunsSteps.php
Apples missing header to other resources that require OpenAI-Beta header.
fixes: #700
> fix(OpenAI): Apply OpenAI-Beta to all Assistant type resources
